default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials[:database][:local][:database] %>
  username: <%= Rails.application.credentials[:database][:local][:username] %>
  password: <%= Rails.application.credentials[:database][:local][:password] %>
  host: <%= Rails.application.credentials[:database][:local][:hostname] %>

production:
  <<: *default
  database: <%= Rails.application.credentials[:database][:rds][:database] %>
  username: <%= Rails.application.credentials[:database][:rds][:username] %>
  password: <%= Rails.application.credentials[:database][:rds][:password] %>
  host: <%= Rails.application.credentials[:database][:rds][:hostname] %>
